---

all:
  hosts:
    localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    current_environment: dev
    ipaadmin_principal: admin
